### ISSUE TITLE
PostgreSQL Archive DB transfer issues.

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#197] opened 2023-05-11 21:54 UTC
Item | Description Deleting selected events works but moving or copying selected events to the archive database causes the screen to come back as incomplete. This issue only happening in PostgreSQL. The process of moving or copying events does complete, but when the page refreshes. It appears it is trying to close the PostgreSQL database and it has already been closed.
-----|-------------
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | 
---
**Expected Behavior:** 
**Current Behavior:**
![2023-05-11_17-49-13](https://github.com/NathanGibbs3/BASE/assets/12111398/c2a22a81-cee2-462e-9941-2d23299d9585)
[php_errors.log](https://github.com/NathanGibbs3/BASE/files/11456588/php_errors.log)
[u_ex230511.log](https://github.com/NathanGibbs3/BASE/files/11456589/u_ex230511.log)

**Comment by mesteele** [comment] 2023-05-18 21:49
Here is BASE in debug mode 1. All I fo is list the events and select 1 event, select move, and then select selected.

$number_sensors = 1

UpdateAlertCache: sensor #1: event.cid = 32859, acid_event.cid = 32822
CacheSensor: INSERT INTO acid_event (sid,cid,signature,timestamp, ip_src,ip_dst,ip_proto, layer4_sport,layer4_dport, sig_name, sig_priority, sig_class_id ) SELECT event.sid as sid, event.cid as cid, signature, timestamp, ip_src, ip_dst, ip_proto, tcp_sport as layer4_sport, tcp_dport as layer4_dport, sig_name, sig_priority, sig_class_id FROM event INNER JOIN signature ON (signature = signature.sig_id) INNER JOIN iphdr ON (event.sid=iphdr.sid AND event.cid=iphdr.cid) LEFT JOIN tcphdr ON (event.sid=tcphdr.sid AND event.cid=tcphdr.cid) WHERE (event.sid = 1 AND event.cid > 32822) AND ip_proto = 6 AND ( NOT ( (sig_name LIKE '(spp_%') OR (sig_name LIKE '(spo_%') OR (sig_name LIKE '(snort_decoder)%') OR (sig_name LIKE '(http_decode)%') OR (sig_name LIKE '(http_inspect)%') OR (sig_name LIKE '(portscan)%') OR (sig_name LIKE '(flow-portscan)%') OR (sig_name LIKE '(frag3)%') OR (sig_name LIKE '(smtp)%') OR (sig_name LIKE '(ftp_pp)%') OR (sig_name LIKE '(telnet_pp)%') OR (sig_name LIKE '(ssh)%') OR (sig_name LIKE '(stream5)%') OR (sig_name LIKE '(dcerpc)%') OR (sig_name LIKE '(dns)%') OR (sig_name LIKE '(ppm)%') ) )
CacheSensor: INSERT INTO acid_event (sid,cid,signature,timestamp, ip_src,ip_dst,ip_proto, layer4_sport,layer4_dport, sig_name, sig_priority, sig_class_id ) SELECT event.sid as sid, event.cid as cid, signature, timestamp, ip_src, ip_dst, ip_proto, udp_sport as layer4_sport, udp_dport as layer4_dport, sig_name, sig_priority, sig_class_id FROM event INNER JOIN signature ON (signature = signature.sig_id) INNER JOIN iphdr ON (event.sid=iphdr.sid AND event.cid=iphdr.cid) LEFT JOIN udphdr ON (event.sid=udphdr.sid AND event.cid=udphdr.cid) WHERE (event.sid = 1 AND event.cid > 32822) AND ip_proto = 17 AND ( NOT ( (sig_name LIKE '(spp_%') OR (sig_name LIKE '(spo_%') OR (sig_name LIKE '(snort_decoder)%') OR (sig_name LIKE '(http_decode)%') OR (sig_name LIKE '(http_inspect)%') OR (sig_name LIKE '(portscan)%') OR (sig_name LIKE '(flow-portscan)%') OR (sig_name LIKE '(frag3)%') OR (sig_name LIKE '(smtp)%') OR (sig_name LIKE '(ftp_pp)%') OR (sig_name LIKE '(telnet_pp)%') OR (sig_name LIKE '(ssh)%') OR (sig_name LIKE '(stream5)%') OR (sig_name LIKE '(dcerpc)%') OR (sig_name LIKE '(dns)%') OR (sig_name LIKE '(ppm)%') ) )
CacheSensor: INSERT INTO acid_event (sid,cid,signature,timestamp, ip_src,ip_dst,ip_proto, sig_name, sig_priority, sig_class_id ) SELECT event.sid as sid, event.cid as cid, signature, timestamp, ip_src, ip_dst, ip_proto, sig_name, sig_priority, sig_class_id FROM event INNER JOIN signature ON (signature = signature.sig_id) INNER JOIN iphdr ON (event.sid=iphdr.sid AND event.cid=iphdr.cid) LEFT JOIN icmphdr ON (event.sid=icmphdr.sid AND event.cid=icmphdr.cid) WHERE (event.sid = 1 AND event.cid > 32822) and ip_proto = 1 AND ( NOT ( (sig_name LIKE '(spp_%') OR (sig_name LIKE '(spo_%') OR (sig_name LIKE '(snort_decoder)%') OR (sig_name LIKE '(http_decode)%') OR (sig_name LIKE '(http_inspect)%') OR (sig_name LIKE '(portscan)%') OR (sig_name LIKE '(flow-portscan)%') OR (sig_name LIKE '(frag3)%') OR (sig_name LIKE '(smtp)%') OR (sig_name LIKE '(ftp_pp)%') OR (sig_name LIKE '(telnet_pp)%') OR (sig_name LIKE '(ssh)%') OR (sig_name LIKE '(stream5)%') OR (sig_name LIKE '(dcerpc)%') OR (sig_name LIKE '(dns)%') OR (sig_name LIKE '(ppm)%') ) )
CacheSensor: INSERT INTO acid_event (sid,cid,signature,timestamp, ip_src,ip_dst,ip_proto, sig_name, sig_priority, sig_class_id ) SELECT event.sid as sid, event.cid as cid, signature, timestamp, ip_src, ip_dst, ip_proto, sig_name, sig_priority, sig_class_id FROM event INNER JOIN signature ON (signature = signature.sig_id) LEFT JOIN iphdr ON (event.sid=iphdr.sid AND event.cid=iphdr.cid) WHERE (NOT (ip_proto IN (1, 6, 17))) AND ( NOT ( (sig_name LIKE '(spp_%') OR (sig_name LIKE '(spo_%') OR (sig_name LIKE '(snort_decoder)%') OR (sig_name LIKE '(http_decode)%') OR (sig_name LIKE '(http_inspect)%') OR (sig_name LIKE '(portscan)%') OR (sig_name LIKE '(flow-portscan)%') OR (sig_name LIKE '(frag3)%') OR (sig_name LIKE '(smtp)%') OR (sig_name LIKE '(ftp_pp)%') OR (sig_name LIKE '(telnet_pp)%') OR (sig_name LIKE '(ssh)%') OR (sig_name LIKE '(stream5)%') OR (sig_name LIKE '(dcerpc)%') OR (sig_name LIKE '(dns)%') OR (sig_name LIKE '(ppm)%') ) ) AND (event.sid = 1 AND event.cid > 32822)
CacheSensor: INSERT INTO acid_event (sid,cid,signature,timestamp, ip_src,ip_dst,ip_proto, sig_name, sig_priority, sig_class_id ) SELECT event.sid as sid, event.cid as cid, signature, timestamp, ip_src, ip_dst, ip_proto, sig_name, sig_priority, sig_class_id FROM event INNER JOIN signature ON (signature = signature.sig_id) LEFT JOIN iphdr ON (event.sid=iphdr.sid AND event.cid=iphdr.cid) WHERE ( (sig_name LIKE '(spp_%') OR (sig_name LIKE '(spo_%') OR (sig_name LIKE '(snort_decoder)%') OR (sig_name LIKE '(http_decode)%') OR (sig_name LIKE '(http_inspect)%') OR (sig_name LIKE '(portscan)%') OR (sig_name LIKE '(flow-portscan)%') OR (sig_name LIKE '(frag3)%') OR (sig_name LIKE '(smtp)%') OR (sig_name LIKE '(ftp_pp)%') OR (sig_name LIKE '(telnet_pp)%') OR (sig_name LIKE '(ssh)%') OR (sig_name LIKE '(stream5)%') OR (sig_name LIKE '(dcerpc)%') OR (sig_name LIKE '(dns)%') OR (sig_name LIKE '(ppm)%') ) AND (event.sid = 1 AND event.cid > 32822)
---------------
Import: sig
Criteria Type: NULL
Criteria Import: Denied.
Import: sig_priority
Criteria Type: NULL
Criteria Import: Denied.
Import: time
Criteria Type: NULL
Criteria Import: Denied.
Import: ip_addr
Criteria Type: NULL
Criteria Import: Denied.
Import: ip_field
Criteria Type: NULL
Criteria Import: Denied.
Import: tcp_port
Criteria Type: NULL
Criteria Import: Denied.
Import: tcp_flags
Criteria Type: NULL
Criteria Import: Denied.
Import: tcp_field
Criteria Type: NULL
Criteria Import: Denied.
Import: udp_port
Criteria Type: NULL
Criteria Import: Denied.
Import: udp_field
Criteria Type: NULL
Criteria Import: Denied.
Import: icmp_field
Criteria Type: NULL
Criteria Import: Denied.
Import: rawip_field
Criteria Type: NULL
Criteria Import: Denied.
Import: data
Criteria Type: NULL
Criteria Import: Denied.
Import: data
Criteria Type: NULL
Property Type: array
Property Import: Allowed.
Back List (Cnt = 3)
Array
(
    [0] => Array
        (
            [0] => 
            [1] => 
            [2] => 
        )

    [1] => Array
        (
            [SCRIPT_NAME] => /base_main.php
            [QUERY_STRING] => 
            [session] => back_list|N;back_list_cnt|i:-1;
        )

    [2] => Array
        (
            [SCRIPT_NAME] => /base_qry_main.php
            [QUERY_STRING] => new=1&layer4=TCP&num_result_rows=-1&sort_order=time_d&submit=Query+DB
            [session] => back_list|N;back_list_cnt|i:-1;sig_type|s:0:"";sig_class|s:0:"";ag|s:0:"";sensor|s:0:"";time|N;time_cnt|s:0:"";ip_addr|N;ip_addr_cnt|s:0:"";layer4|s:3:"TCP";ip_field|N;ip_field_cnt|s:0:"";tcp_port|N;tcp_port_cnt|s:0:"";tcp_field|N;tcp_field_cnt|s:0:"";udp_port|N;udp_port_cnt|s:0:"";udp_field|N;udp_field_cnt|s:0:"";icmp_field|N;icmp_field_cnt|s:0:"";rawip_field|N;rawip_field_cnt|s:0:"";data|N;data_cnt|s:0:"";data_encode|a:2:{i:0;s:0:"";i:1;s:0:"";}
        )

    [3] => Array
        (
            [SCRIPT_NAME] => /base_qry_main.php
            [QUERY_STRING] => search=1&prev_sort_order=time_d&action_chk_lst%5B0%5D=%230-%281-35%29&action_lst%5B0%5D=%230-%281-35%29&action_lst%5B1%5D=%231-%281-41%29&action_lst%5B2%5D=%232-%281-46%29&action_lst%5B3%5D=%233-%281-50%29&action_lst%5B4%5D=%234-%281-53%29&action_lst%5B5%5D=%235-%281-55%29&action_lst%5B6%5D=%236-%281-67%29&action_lst%5B7%5D=%237-%281-77%29&action_lst%5B8%5D=%238-%281-83%29&action_lst%5B9%5D=%239-%281-87%29&action_lst%5B10%5D=%2310-%281-90%29&action_lst%5B11%5D=%2311-%281-100%29&action_lst%5B12%5D=%2312-%281-107%29&action_lst%5B13%5D=%2313-%281-112%29&action_lst%5B14%5D=%2314-%281-119%29&action_lst%5B15%5D=%2315-%281-124%29&action_lst%5B16%5D=%2316-%281-127%29&action_lst%5B17%5D=%2317-%281-135%29&action_lst%5B18%5D=%2318-%281-141%29&action_lst%5B19%5D=%2319-%281-146%29&action_lst%5B20%5D=%2320-%281-155%29&action_lst%5B21%5D=%2321-%281-160%29&action_lst%5B22%5D=%2322-%281-163%29&action_lst%5B23%5D=%2323-%281-173%29&action_lst%5B24%5D=%2324-%281-176%29&action_lst%5B25%5D=%2325-%281-185%29&action_lst%5B26%5D=%2326-%281-191%29&action_lst%5B27%5D=%2327-%281-194%29&action_lst%5B28%5D=%2328-%281-197%29&action_lst%5B29%5D=%2329-%281-205%29&action_lst%5B30%5D=%2330-%281-216%29&action_lst%5B31%5D=%2331-%281-219%29&action_lst%5B32%5D=%2332-%281-228%29&action_lst%5B33%5D=%2333-%281-233%29&action_lst%5B34%5D=%2334-%281-235%29&action_lst%5B35%5D=%2335-%281-246%29&action_lst%5B36%5D=%2336-%281-249%29&action_lst%5B37%5D=%2337-%281-258%29&action_lst%5B38%5D=%2338-%281-262%29&action_lst%5B39%5D=%2339-%281-270%29&action_lst%5B40%5D=%2340-%281-274%29&action_lst%5B41%5D=%2341-%281-282%29&action_lst%5B42%5D=%2342-%281-288%29&action_lst%5B43%5D=%2343-%281-294%29&action_lst%5B44%5D=%2344-%281-299%29&action_lst%5B45%5D=%2345-%281-304%29&action_lst%5B46%5D=%2346-%281-308%29&action_lst%5B47%5D=%2347-%281-317%29&action=archive_alert2&action_arg=&submit=Selected&caller=&num_result_rows=29583¤t_view=0
            [session] => back_list|N;back_list_cnt|i:-1;sig_type|s:0:"";sig_class|s:0:"";ag|s:0:"";sensor|s:0:"";time|N;time_cnt|s:0:"";ip_addr|N;ip_addr_cnt|i:0;layer4|s:3:"TCP";ip_field|N;ip_field_cnt|s:0:"";tcp_port|N;tcp_port_cnt|i:0;tcp_field|N;tcp_field_cnt|i:0;udp_port|N;udp_port_cnt|s:0:"";udp_field|N;udp_field_cnt|s:0:"";icmp_field|N;icmp_field_cnt|s:0:"";rawip_field|N;rawip_field_cnt|s:0:"";data|N;data_cnt|i:0;data_encode|a:2:{i:0;s:0:"";i:1;s:0:"";}
        )

)
Basic Analysis and Security Engine (BASE)
Home | Search | Back
         URL: '/base_qry_main.php?search=1&prev_sort_order=time_d&action_chk_lst%5B0%5D=%230-%281-35%29&action_lst%5B0%5D=%230-%281-35%29&action_lst%5B1%5D=%231-%281-41%29&action_lst%5B2%5D=%232-%281-46%29&action_lst%5B3%5D=%233-%281-50%29&action_lst%5B4%5D=%234-%281-53%29&action_lst%5B5%5D=%235-%281-55%29&action_lst%5B6%5D=%236-%281-67%29&action_lst%5B7%5D=%237-%281-77%29&action_lst%5B8%5D=%238-%281-83%29&action_lst%5B9%5D=%239-%281-87%29&action_lst%5B10%5D=%2310-%281-90%29&action_lst%5B11%5D=%2311-%281-100%29&action_lst%5B12%5D=%2312-%281-107%29&action_lst%5B13%5D=%2313-%281-112%29&action_lst%5B14%5D=%2314-%281-119%29&action_lst%5B15%5D=%2315-%281-124%29&action_lst%5B16%5D=%2316-%281-127%29&action_lst%5B17%5D=%2317-%281-135%29&action_lst%5B18%5D=%2318-%281-141%29&action_lst%5B19%5D=%2319-%281-146%29&action_lst%5B20%5D=%2320-%281-155%29&action_lst%5B21%5D=%2321-%281-160%29&action_lst%5B22%5D=%2322-%281-163%29&action_lst%5B23%5D=%2323-%281-173%29&action_lst%5B24%5D=%2324-%281-176%29&action_lst%5B25%5D=%2325-%281-185%29&action_lst%5B26%5D=%2326-%281-191%29&action_lst%5B27%5D=%2327-%281-194%29&action_lst%5B28%5D=%2328-%281-197%29&action_lst%5B29%5D=%2329-%281-205%29&action_lst%5B30%5D=%2330-%281-216%29&action_lst%5B31%5D=%2331-%281-219%29&action_lst%5B32%5D=%2332-%281-228%29&action_lst%5B33%5D=%2333-%281-233%29&action_lst%5B34%5D=%2334-%281-235%29&action_lst%5B35%5D=%2335-%281-246%29&action_lst%5B36%5D=%2336-%281-249%29&action_lst%5B37%5D=%2337-%281-258%29&action_lst%5B38%5D=%2338-%281-262%29&action_lst%5B39%5D=%2339-%281-270%29&action_lst%5B40%5D=%2340-%281-274%29&action_lst%5B41%5D=%2341-%281-282%29&action_lst%5B42%5D=%2342-%281-288%29&action_lst%5B43%5D=%2343-%281-294%29&action_lst%5B44%5D=%2344-%281-299%29&action_lst%5B45%5D=%2345-%281-304%29&action_lst%5B46%5D=%2346-%281-308%29&action_lst%5B47%5D=%2347-%281-317%29&action=archive_alert2&action_arg=&submit=Selected&caller=&num_result_rows=29583&current_view=0'
         (referred by: 'http://winids/base_qry_main.php?new=1&layer4=TCP&num_result_rows=-1&sort_order=time_d&submit=Query+DB')
         PARAMETERS: 'search=1&prev_sort_order=time_d&action_chk_lst%5B0%5D=%230-%281-35%29&action_lst%5B0%5D=%230-%281-35%29&action_lst%5B1%5D=%231-%281-41%29&action_lst%5B2%5D=%232-%281-46%29&action_lst%5B3%5D=%233-%281-50%29&action_lst%5B4%5D=%234-%281-53%29&action_lst%5B5%5D=%235-%281-55%29&action_lst%5B6%5D=%236-%281-67%29&action_lst%5B7%5D=%237-%281-77%29&action_lst%5B8%5D=%238-%281-83%29&action_lst%5B9%5D=%239-%281-87%29&action_lst%5B10%5D=%2310-%281-90%29&action_lst%5B11%5D=%2311-%281-100%29&action_lst%5B12%5D=%2312-%281-107%29&action_lst%5B13%5D=%2313-%281-112%29&action_lst%5B14%5D=%2314-%281-119%29&action_lst%5B15%5D=%2315-%281-124%29&action_lst%5B16%5D=%2316-%281-127%29&action_lst%5B17%5D=%2317-%281-135%29&action_lst%5B18%5D=%2318-%281-141%29&action_lst%5B19%5D=%2319-%281-146%29&action_lst%5B20%5D=%2320-%281-155%29&action_lst%5B21%5D=%2321-%281-160%29&action_lst%5B22%5D=%2322-%281-163%29&action_lst%5B23%5D=%2323-%281-173%29&action_lst%5B24%5D=%2324-%281-176%29&action_lst%5B25%5D=%2325-%281-185%29&action_lst%5B26%5D=%2326-%281-191%29&action_lst%5B27%5D=%2327-%281-194%29&action_lst%5B28%5D=%2328-%281-197%29&action_lst%5B29%5D=%2329-%281-205%29&action_lst%5B30%5D=%2330-%281-216%29&action_lst%5B31%5D=%2331-%281-219%29&action_lst%5B32%5D=%2332-%281-228%29&action_lst%5B33%5D=%2333-%281-233%29&action_lst%5B34%5D=%2334-%281-235%29&action_lst%5B35%5D=%2335-%281-246%29&action_lst%5B36%5D=%2336-%281-249%29&action_lst%5B37%5D=%2337-%281-258%29&action_lst%5B38%5D=%2338-%281-262%29&action_lst%5B39%5D=%2339-%281-270%29&action_lst%5B40%5D=%2340-%281-274%29&action_lst%5B41%5D=%2341-%281-282%29&action_lst%5B42%5D=%2342-%281-288%29&action_lst%5B43%5D=%2343-%281-294%29&action_lst%5B44%5D=%2344-%281-299%29&action_lst%5B45%5D=%2345-%281-304%29&action_lst%5B46%5D=%2346-%281-308%29&action_lst%5B47%5D=%2347-%281-317%29&action=archive_alert2&action_arg=&submit=Selected&caller=&num_result_rows=29583&current_view=0'
         CLIENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42
         BASE VERSION: 1.4.5-0.0.1 (Jayme)+2023-04-30
         SESSION ID: 331telrim3c68q1v0ibrshiak0( 3698 bytes )
         SCRIPT : /base_qry_main.php
         
Sensor: 

AG: 

signature

time struct ():

IP addresses (0):

IP fields ():

TCP ports (0):

TCP flags

TCP fields (0):

UDP ports ():

UDP fields ():

ICMP fields ():

RawIP field ():

Data (0):
            new: ''   
            submit: 'Selected'
            sort_order: 'time_d'
            num_result_rows: ''  current_view: ''
            layer4: ''  caller: ''
            action: ''  action_arg: ''
            
$sig[0] = ""
$sig[1] = ""
$sig[2] = ""
$sig[3] = ""

==== ACTION ======
context = 1


==== Archive alert(s) (move) Alerts ========
num_alert = 29583
action_sql = SELECT acid_event.sid, acid_event.cid FROM acid_event WHERE 1 = 1 AND acid_event.ip_proto= '6'
action_op = Selected
action_arg =
action_param =
context = 1
limit_start = -1
limit_offset = -1
Action Capabilities
Mail:	1
Mime:	1
Archive:	1
Debug delay active BASE resmuing in 60 seconds.

using_blobs =
NewBASEDBConnection: Req DB type: postgres
NewBASEDBConnection: FIN DB type: postgres
NewBASEDBConnection: DB Driver: postgres
NewBASEDBConnection: Req DAL path = 'd:\winids\adodb5'
NewBASEDBConnection: DAL Load: 'd:\winids\adodb5adodb.inc.php'
ChkLib: Chk: d:\winids\adodb5\adodb-errorhandler.inc.php
ChkLib: Lib: d:\winids\adodb5\adodb-errorhandler.inc.php found.
NewBASEDBConnection: Checking for DB abstraction lib in 'd:\winids\adodb5\adodb.inc.php'
ChkLib: Chk: d:\winids\adodb5\adodb.inc.php
ChkLib: Lib: d:\winids\adodb5\adodb.inc.php found.

Gathering elements from 1 alert blobs
Blob Item(s): 1 - 35,
Array
(
    [0] => Array
        (
            [0] => 1
            [1] => fireeye.com/blog/threat-research/2019/01/bypassing-network-restrictions-through-rdp-tunneling.html
            [2] => url
        )

)
Array
(
    [0] => INSERT INTO event (sid,cid,signature,timestamp) VALUES (1, 35, '3', '2023-05-02 11:48:30.003-04')
    [1] => INSERT INTO iphdr (sid, cid, ip_src, ip_dst, ip_ver, ip_hlen, ip_tos, ip_len, ip_id,ip_flags, ip_off, ip_ttl, ip_proto,ip_csum) VALUES (1, 35, '3530634174', '3232235779','4','5','0','83','15656','0','0','112','6','1442')
    [2] => INSERT INTO tcphdr (sid, cid, tcp_sport, tcp_dport, tcp_seq, tcp_ack, tcp_off, tcp_res, tcp_flags, tcp_win, tcp_csum, tcp_urp) VALUES (1, 35, '60273', '4000','2818265252','3732948731','5','0','24','1028','16717','0')
    [3] => INSERT INTO data (sid,cid, data_payload) VALUES (1, 35, '0300002B26E00000000000436F6F6B69653A206D737473686173683D68656C6C6F0D0A0100080003000000')
)
xxx jl: archive_cnt = 4
sql_cnt = 4
$number_sensors = 1

UpdateAlertCache: sensor #1: event.cid = 1768, acid_event.cid = 1768
NewBASEDBConnection: Req DB type: postgres
NewBASEDBConnection: FIN DB type: postgres
NewBASEDBConnection: DB Driver: postgres
NewBASEDBConnection: Req DAL path = 'd:\winids\adodb5'
NewBASEDBConnection: DAL Load: 'd:\winids\adodb5adodb.inc.php'
ChkLib: Chk: d:\winids\adodb5\adodb-errorhandler.inc.php
ChkLib: Lib: d:\winids\adodb5\adodb-errorhandler.inc.php found.
NewBASEDBConnection: Checking for DB abstraction lib in 'd:\winids\adodb5\adodb.inc.php'
ChkLib: Chk: d:\winids\adodb5\adodb.inc.php
ChkLib: Lib: d:\winids\adodb5\adodb.inc.php found.

**Comment by mesteele** [comment] 2023-05-18 22:28
This is happening under:
PHP 5.6.40 - adodb 5.20.20 using PostgreSQL 15.2
Log for above.
[php_errors5.log](https://github.com/NathanGibbs3/BASE/files/11511919/php_errors5.log)

PHP 8.2.6 - adodb 5.22.5 using PostgreSQL 15.2
Log for above.
[php_errors8.log](https://github.com/NathanGibbs3/BASE/files/11511923/php_errors8.log)

Not sure when this started happening, but it looks like an issue with BASE opening/closing at least the PostgreSQL 15.2 database.

All I did for each was Delete the PHP error log, list the events, select 1 event and used the move. I can go back and check the Archive database and it does move the event.

**Comment by NathanGibbs3** [comment] 2023-05-19 12:11
FYI: you 'should' be able to run newer versions of ADOdb on PHP 5x up to a certain point.
[See the wiki page](https://github.com/NathanGibbs3/BASE/wiki/ADOdb-version-requirements-by-PHP-Version) on that.
Most of the results on that page have been verified by Travis-CI runs.  Where we don't know, the verified column is marked as No.
That may help you, as you would have the benefits of running on newer ADOdb code.

Either way, I'll need to figure our why we lose the PostgreSQL DB connection after the archive DB action.

**Comment by mesteele** [comment] 2023-05-19 13:48
The wiki says that the max ADOdb version for PHP5 is 5.21.4 but BASE can't handle that version. The main BASE screen does come up but any links past that give a blank screen.

Hopefully it is a simple fix :)

**Comment by mesteele** [comment] 2023-05-19 15:44
I just tried it with PHP 7 and same result with moving on IIS and PostgreSQL.

BASE FATAL ERROR:
BASE DB Query Fail: NULL Recordset NO ADOdb Error Msg

**Comment by NathanGibbs3** [comment] 2023-05-19 19:18
This is probably not the cause, however we need to eliminate anything obviously simple.
Are the `$db_connect_method` settings in your configurations on MySQL & PostgreSQL the same?

**Comment by mesteele** [comment] 2023-05-19 20:08
They are both set to:
$db_connect_method = 1;

For PostgreSQL I change the below from 0 to 1 and the extra tables are installed:

/* Use referential integrity
 *   1  : use
 *   0  : ignore (not installed)
 *
 * Note: Only PostgreSQL and MS-SQL Server databases support
 *       referential integrity.  Use the associated
 *       create_acid_tbls_?_extra.sql script to add this
 *       functionality to the database.
 *
 *       Referential integrity will greatly improve the
 *       speed of record deletion, but also slow record
 *       insertion.
 */
$use_referential_integrity = 1;

**Closed** 2023-05-30 22:24 UTC
Labels: bug, invalid, Prod, LCB-TechDebt, DB, Stability
